controller_list:
  - name: fake_ur10_arm_controller
    joints:
      - ur10_arm_shoulder_pan_joint
      - ur10_arm_shoulder_lift_joint
      - ur10_arm_elbow_joint
      - ur10_arm_wrist_1_joint
      - ur10_arm_wrist_2_joint
      - ur10_arm_wrist_3_joint
  - name: fake_robotiq_hand_controller
    joints:
      - robotiq_palm_finger_1_joint
      - robotiq_finger_1_joint_1
      - robotiq_finger_1_joint_2
      - robotiq_finger_1_joint_3
      - robotiq_palm_finger_2_joint
      - robotiq_finger_2_joint_1
      - robotiq_finger_2_joint_2
      - robotiq_finger_2_joint_3
      - robotiq_finger_middle_joint_1
      - robotiq_finger_middle_joint_2
      - robotiq_finger_middle_joint_3